/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class CharsPercTest {
    @Test public void countTest1() {
        CharsPercentage classUnderTest = new CharsPercentage();
        assertEquals(classUnderTest.count("qwerty"), 100.0f, "app counts for 100%");
    }
    
    @Test public void countTest2() {
        CharsPercentage classUnderTest = new CharsPercentage();
        assertEquals(classUnderTest.count("12345"), 0.0f, "app counts for 0%");
    }
  
    @Test public void countTest3() {
        CharsPercentage classUnderTest = new CharsPercentage();
        assertEquals(classUnderTest.count("12345abcdd"), 50.0f, "app counts for 50%");
    }
    
//    @Test public void () {
//        CharsPercentage classUnderTest = new CharsPercentage();
//        assertEquals(classUnderTest.count("12345"), "The percentage of Chars in the file is - 0.00%");
//    }
}
